### ISSUE TITLE
Template parsing errors when running docker-gc

### ISSUE THREAD

**Issue by buckett** [spotify/docker-gc#105]
## Description

When running docker-gc I get a list of template errors logged:

    Template parsing error: template: :1:2: executing "" at <.Tags>: Tags is not a field of struct type types.ImageInspect
    Removing image 010a096fc84648e91a06c39a451f333b543d71dc01f3e8ac83bfdf7a39aaf18f 

## How to reproduce

Use an old version of docker-gc with a newer version of docker.

## What do you expect

The command to run without producing any errors.

## What happened instead

I got multiple errors.

## Software:

- bash version: 4.3.11(1)
- docker 1.9.1
- docker-gc (e194bc0)

**Comment by buckett** [comment]
This issue is fixed by upgrading to docker-gc 3f8e3f0 which works correctly. I haven't tracked down which commit actually fixed it.

I reported this so that if someone else has the same issue they can see an upgrade is the easy fix.

**Comment by mattnworb** [comment]
@buckett thanks for the heads up. I think it might have been fixed by https://github.com/spotify/docker-gc/pull/76
