### ISSUE TITLE
Incorrect process detection ("Process is already running")

### ISSUE THREAD

**Issue by drewmnoel** [spotify/docker-gc#111]
## Description

The new process detection (in 420558e74413b63aa479a31a44d6039d6b255d66) seems to be problematic when run with `sudo`. This is probably because `sudo` creates another copy of the process entry with root permissions, and then runs *that*. So there will be two copies in the process list.

If I switch to root, the command works just fine.

## How to reproduce

1. Run `sudo docker-gc`

## What do you expect

Command completes successfully

## What happened instead

`docker-gc` detects the original `sudo` request as a separate process, and refuses to run

## Software:

- bash version: `GNU bash, version 4.3.42(1)-release`
- fgrep version: `grep (GNU grep) 2.25`
- sudo version: `Sudo version 1.8.16`

## Full backtrace

```text
$ sudo docker-gc
[Mon Jun 27 11:47:26 EDT 2016] : docker-gc : Process is already running with PID 6817
```

**Comment by mattnworb** [comment]
hey @drewmnoel thanks for the heads up. I've reverted that previous change at https://github.com/spotify/docker-gc/pull/112
