### ISSUE TITLE
Test sandbox

### ISSUE THREAD

**Issue by waltervargas** [spotify/docker-gc#113]
## Description
I want to test the behaviour of this component before put it on my infrastructure, do you have a load testing script to increase the number of containers and memory consumption ?

## What do you expect

I am requesting for an advice.

**Comment by mattnworb** [comment]
Hi @waltervargas , you might find https://github.com/spotify/docker-stress useful. It can create a ton of containers for you. I believe the script will also clean up the containers afterwards, but you should be able to easily modify that logic to leave them around for docker-gc to deal with.
