### ISSUE TITLE
df: ‘/var/lib/docker’: No such file or directory

### ISSUE THREAD

**Issue by Pablohn26** [spotify/docker-gc#126]
## Description

Finishing the clean up, I get this error
> df: ‘/var/lib/docker’: No such file or directory

My _Docker Root Dir_ is changed but seems process does not follow it, just go to default _Docker Root Dir_ (/var/lib/docker/)

## How to reproduce

Change _Docker Root Dir_
Launch the clean up

## What do you expect

No error. 

## What happened instead

> df: ‘/var/lib/docker’: No such file or directory
> Finished Cleanup (bytes free )

## Software:

- bash version: GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
- OS version: Debian 8.5
- docker version: Docker version 1.12.1, build 23cf638

## Full backtrace

```/var/discourse/launcher cleanup

The following command will
- Delete all docker images for old containers
- Delete all stopped and orphan containers

Are you sure (Y/n): y
df: ‘/var/lib/docker’: No such file or directory
Starting Cleanup (bytes free )
Unable to find image 'samsaffron/docker-gc:latest' locally
latest: Pulling from samsaffron/docker-gc

0f4d770cd333: Pull complete 
a3ed95caeb02: Pull complete 
6a2ea02ca5be: Pull complete 
bc4c30afebbb: Pull complete 
Digest: sha256:1efd5febba28f881c815c37005b09c67fce0fa62d583b82790b0a0fe82cad999
Status: Downloaded newer image for samsaffron/docker-gc:latest
df: ‘/var/lib/docker’: No such file or directory
Finished Cleanup (bytes free )

```

**Comment by mattnworb** [comment]
Hi @Pablohn26, [the docker-gc script in this repo](https://github.com/spotify/docker-gc/blob/master/docker-gc) never calls `df`. 

Perhaps you meant to report this against https://github.com/discourse/discourse_docker ?

**Comment by Pablohn26** [comment]
You are right. 

Sorry about that and thanks for the info.
