### ISSUE TITLE
Make docker-gc work as non-root

### ISSUE THREAD

**Issue by cweiske** [spotify/docker-gc#138]
## Description

`docker-gc` can only be run as root because it wants to write its process ID into `/var/run/`, which writable by root only. This was added in #39.

## How to reproduce

Run `docker-gc` as non-root user.

## What do you expect

`docker-gc` works if the current user is part of the `docker` group.

## What happened instead

```
$ LC_ALL=C docker-gc --help
/usr/sbin/docker-gc: line 67: /var/run/dockergc: Permission denied
```

## Software:

- docker-gc: git version `89b5248a5c9b43b7ad16bfcfa499c04c5ee250b8`
- ubuntu 16.04
- docker 1.12.1

**Comment by soredake** [comment]
Launch it like this `PID_DIR="$XDG_RUNTIME_DIR" docker-gc`

**Comment by sanvila** [comment]
If I do that, I get this:

`-bash: docker-gc: command not found`

Non-root users do not usually have /usr/sbin in the PATH. To be really non-root-friendly, the executable should be in /usr/bin.
