### ISSUE TITLE
map in docker binaries from host

### ISSUE THREAD

**Issue by stephanlindauer** [spotify/docker-gc#153]
instead of downloading a specific docker version in the Dockerfile build, you could just map in the docker binaries from the host, like so:
```-v /usr/bin/docker:/usr/bin/docker```

**Comment by mgvazquez** [comment]
+1
But this is tricky; on RHEL based OS, the binary it's on '/bin/docker'.

Can be en ENV with a default

**Comment by stephanlindauer** [comment]
yeah i mean it could be just mentioned in the docs that this is possible:
```
-v $(which docker):/usr/bin/docker
```
