### ISSUE TITLE
Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by toidi** [spotify/docker-gc#158]
## Description

With recent updates docker-gc is unable to communicate with docker engine server.

## How to reproduce

Use latest version of docker-gc with docker 1.10.x

## What do you expect

Ideally docker-gc should work with most recent docker engine releases.

As a suggestion - tag docker-gc releases,
thus docker-gc users can pin version and upgrade when they are ready.

## What happened instead

Error response from daemon.

## Software:

Docker 1.10.3, `spotify/docker-gc:latest`

## Full backtrace

```
$ sudo docker run --rm -e GRACE_PERIOD_SECONDS=86400 -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

**Comment by benoahriz** [comment]
Same issue I ran into using a pinned version of docker.  It would be nice to be able to pin on a version of docker-gc container to match our docker server versions.
