### ISSUE TITLE
docker-gc is deleting networks required by some containers

### ISSUE THREAD

**Issue by tarikgwa** [spotify/docker-gc#174]
Docker-gc is removing networks during docker initialization, meaning that some containers cannot be started due to missing networks.

The following has been reproduced in a replica of the host:

```
/var/log/auth.log:Jul  6 12:03:20 localhost snoopy[3469]: root>root:/var/lib/docker-gc docker network rm ems_ems-ua
/var/log/auth.log:Jul  6 12:03:21 localhost snoopy[3524]: root>root:/var/lib/docker-gc docker network rm net-db-maintenance
/var/log/auth.log:Jul  6 12:03:22 localhost snoopy[3571]: root>root:/var/lib/docker-gc docker network rm reputationmonitor_platform-rm

```
How can we resolve that issue that hurt our environments ?

Thank You

**Comment by Jellby** [comment]
I wonder if this could be the reason why I my gitlab CI runner fails with "ERROR: Job failed (system failure): persistent connection closed" when I have docker-gc in cron.hourly...
