### ISSUE TITLE
ValueError: time data '2015-06-17' does not match format '%Y-%m-%dT%H:%M:%S'

### ISSUE THREAD

**Issue by maakuth** [spotify/docker-gc#18]
sudo docker-gc
    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
      File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
        (data_string, format))
    ValueError: time data '2015-06-17' does not match format '%Y-%m-%dT%H:%M:%S'

This is an error I get from freshly installed docker-gc on Ubuntu 15.04 amd64, Docker 1.7.0. My first guess was something locale related, but looking at the specificity of the expected format, I suppose it could be due to Docker (or some other piece of software along the way) changing some date format to a less accurate form. I have written a /etc/docker-gc-exclude file. I'll be happy to supply additional details if you need some.

**Comment by maakuth** [comment]
Indeed, changing the strptime format string in the ElapsedTime function from "%Y-%m-%dT%H:%M:%S" to "%Y-%m-%d" fixed it. I suppose docker printout has changed in 1.7.0 or in other recent release.

**Comment by rtrauntvein** [comment]
+1

**Comment by erikthered** [comment]
It looks like this is actually a Docker bug https://github.com/docker/docker/issues/14164
