### ISSUE TITLE
LOG_TO_SYSLOG unrecognized option

### ISSUE THREAD

**Issue by therock** [spotify/docker-gc#188]
## Description

when running the docker container with env **LOG_TO_SYSLOG=1** it fails with unrecognized option to logger inside the container

## How to reproduce

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc:ro -e GRACE_PERIOD_SECONDS=86400 -e MINIMUM_IMAGES_TO_SAVE=2 -e LOG_TO_SYSLOG=1 -e REMOVE_VOLUMES=1 spotify/docker-gc

## What happened

Unable to find image 'spotify/docker-gc:latest' locally
latest: Pulling from spotify/docker-gc
d270e8c9ade8: Pull complete
5f8a41eacc88: Pull complete
909e247a470d: Pull complete
Digest: sha256:907444011125a2b5116f768e2f33b30a6e706271f7f1240c7f671486aa29f093
Status: Downloaded newer image for spotify/docker-gc:latest
```
logger: unrecognized option: i
BusyBox v1.23.2 (2017-01-20 12:25:32 GMT) multi-call binary.

Usage: logger [OPTIONS] [MESSAGE]

Write MESSAGE (or stdin) to syslog

	-s	Log to stderr as well as the system log
	-t TAG	Log using the specified tag (defaults to user name)
	-p PRIO	Priority (numeric or facility.level pair)
```

**Comment by davidxia** [comment]
@mattnworb Do you know where the `-i` came [from here](https://github.com/spotify/docker-gc/pull/64/files#diff-c5cbd2ce5d956e82a9d9c1479c00799bR155)? Should we just remove it?

**Comment by mattnworb** [comment]
Looks like that flag is not supported in some versions or platforms 

http://man7.org/linux/man-pages/man1/logger.1.html

I’m not sure what busybox comes with.
