### ISSUE TITLE
fails with volume /etc on docker for mac

### ISSUE THREAD

**Issue by jkt628** [spotify/docker-gc#190]
## Description

https://github.com/spotify/docker-gc/blame/master/README.md#L190 mounts the docker socket and /etc.  current [Docker for Mac](https://store.docker.com/editions/community/docker-ce-desktop-mac) fails; however, avoiding /etc works fine, e.g.,
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc
```

## How to reproduce

```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro -v /etc:/etc:ro spotify/docker-gc
```

## What do you expect

garbage collection

## What happened instead

```text
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/containers/ffac22f926b0cc794c2271cfabc2026912d6c8950b4fc75b487cece743ce2adc/hostname\\\" to rootfs \\\"/var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged\\\" at \\\"/var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged/etc/hostname\\\" caused \\\"open /var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged/etc/hostname: read-only file system\\\"\"": unknown.
```

## Software:

- bash version: GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
- Docker for Mac version: 18.03.1-ce-mac65 (24312)

## Full backtrace

```text
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/containers/ffac22f926b0cc794c2271cfabc2026912d6c8950b4fc75b487cece743ce2adc/hostname\\\" to rootfs \\\"/var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged\\\" at \\\"/var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged/etc/hostname\\\" caused \\\"open /var/lib/docker/overlay2/023952afd9b7b4537194945d7ae09b3136a4dc1050809e6f1311ac76518b5905/merged/etc/hostname: read-only file system\\\"\"": unknown.
```

**Comment by idangozlan** [comment]
+ 1

**Comment by parkr** [comment]
That's because `/etc` is a symlink to `/private/etc` on a Mac. Try `-v /private/etc:/etc:ro`.

Additionally, while the Docker team has done a wonderful job hiding this fact to make the experience as native-feeling as possible, Docker for Mac runs a Linux VM and syncs your files from your Mac to the Linux VM. It only syncs _some_ of the files, so you have to ensure the directory or file you want to mount as a volume is accessible **in the VM**. If you go to Docker for Mac's Preferences and choose "File Sharing," you should see `/private` in that list. This will allow you to mount `/private/etc`.

**Comment by idangozlan** [comment]
@parkr unfortunately it's not solving the issue. thanks for trying help :)

**Comment by ostrgard** [comment]
@parkr, I've tried `/private/etc` instead of `/etc`, and made sure `/private` is in the list under File Sharing. 

I'm still getting same error. Any other ideas?

**Comment by parkr** [comment]
If you are using Docker for Mac, go to Preferences and check which directories are mounted to your VM. It may be the case that your Linux VM (where containers actually run in Docker for Mac) has not mounted /private/etc.
