### ISSUE TITLE
Docker gc lists images to remove which are present in exclude file

### ISSUE THREAD

**Issue by sandeep-paliwal** [spotify/docker-gc#191]
## Description
Image mentioned in /etc/docker-gc-exclude is not getting honoured by docker-gc and it shows up as image which will be removed.

[Add feature/bug description here]

## How to reproduce
I am running docker-gc as docker container with following command to test out docker-gc run

`docker run --rm --userns host -e GRACE_PERIOD_SECONDS=60 -e DRY_RUN=1 -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc`

I have exclude file created at following location /etc/docker-gc-exclude. This file has following content

> 99dea4a29c24
> spotify/cassandra:latest
> redis:.*

When I run docker-gc with the command mentioned above I see following output in console

> [2018-07-24T06:12:05] [INFO] : The following image would have been removed sha256:481995377a044d40ca3358e4203fe95eca1d58b98a1d4c2d9cec51c0c4569613 [redis:2.8]

## What do you expect

As I had mentioned redis:.* in exclude file I expected the image name should not show up as one which will be removed

## What happened instead

[Describe the actual results]

## Software:

- bash version: [Add bash version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by r3r57** [comment]
I can confirm that this currently doesn't work as expected. [`compute_exclude_ids()`](https://github.com/spotify/docker-gc/blob/c5a3ad431792d4aeeea4a404ded128fd01649129/docker-gc#L111) seems to work properly, but its result is not correctly processed later.
