### ISSUE TITLE
Any particular reason for abandoning docker-gc

### ISSUE THREAD

**Issue by mbrooks** [spotify/docker-gc#207]
I'm curious if there is a particular reason for Spotify to abandon the docker-gc project internally. Is there another tool that works better? Was it replaced with `docker --prune`?

I think it would be helpful to note what Spotify is now using on the issue.

**Comment by Quantum-Sicarius** [comment]
Are any alternative projects or forks available?

**Comment by dazdaz** [comment]
I'd also like to know of any alternative projects and why spotify abandonded this project.

**Comment by Hillkorn** [comment]
> I'd also like to know of any alternative projects and why spotify abandonded this project.

I guess the alternative is the build in `docker prune`

**Comment by strowi** [comment]
for anyone interested, we just replaced the spotify-gc image with a cron-container that runs a regualr "docker image prune -a".
