### ISSUE TITLE
Doc should mention it needs to be run as root

### ISSUE THREAD

**Issue by mpe** [spotify/docker-gc#28]
When built as a debian package it creates `/var/lib/docker-gc/` with perms `drwxr-xr-x` and owned by `root`.

The script then tries to write to this directory, which fails if `docker-gc` is run as a regular user, eg:

```
$ /usr/sbin/docker-gc 
/usr/sbin/docker-gc: line 111: containers.all: Permission denied
```

**Comment by jaakkytt** [comment]
Suggest granting access to relevant files instead of running as root should be the recommended way described in README.

**Comment by davidxia** [comment]
@jaakkytt yea good suggestion. DOne
