### ISSUE TITLE
Support execution from OS X hosts via boot2docker.

### ISSUE THREAD

**Issue by bripkens** [spotify/docker-gc#32]
Unfortunately `docker-gc` does not seem to work when used in combination with boot2docker even though the script exits with a `0` status code.

```
$ docker ps -a
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS                      PORTS               NAMES
e2ef0285ccb5        redis:latest               "/entrypoint.sh redi   7 hours ago          Exited (0) 7 hours ago                          dock-redis
631656e621e7        mysql:latest               "\"/entrypoint.sh sh   10 days ago          Exited (1) 10 days ago                          ecstatic_mccarthy
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc
$ docker ps -a
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS                          PORTS               NAMES
e2ef0285ccb5        redis:latest               "/entrypoint.sh redi   7 hours ago          Exited (0) 7 hours ago                              dock-redis
631656e621e7        mysql:latest               "\"/entrypoint.sh sh   10 days ago          Exited (1) 10 days ago                              ecstatic_mccarthy
```

**Comment by johnswanson** [comment]
Try running `docker run spotify/docker-gc sh -c "wc -l /bin/docker"`. Is the output `0 /bin/docker`? I think you're seeing #35 and running an empty script "successfully." Try merging in #34, or just manually edit the Dockerfile so curl either follows redirects or points to the correct URL (docker.io -> docker.com), rebuild, and try again.

**Comment by bripkens** [comment]
Thanks @johnswanson, this is indeed what happens.

**Comment by mbruggmann** [comment]
This was fixed in #34.

**Comment by bripkens** [comment]
Yes works like a charm. Thanks!

**Comment by bripkens** [comment]
And integrated into [dock](https://github.com/bripkens/dock/commit/1342f27b7b9cf11ae0eb382f59c7bbf51907e12d).

Thank you for docker-gc! :)
