### ISSUE TITLE
RHEL support would be much appreciated

### ISSUE THREAD

**Issue by buley** [spotify/docker-gc#33]
Our production RHEL docker bloat is pretty hellacious. I would be able to hardly "contain" myself were I able to welcome `docker-gc` into my CentOS boxen to help clean up.

Thanks in advance for your consideration of this feature request.

**Comment by davidxia** [comment]
@buley I have no idea how to make RPM packages. Any PR would be welcome though.

**Comment by konstruktoid** [comment]
See #58 by @keis

**Comment by mattnworb** [comment]
With #58 merged I think this should be addressed; you can clone the source and should be able to build the RPM manually. 

@buley feel free to let us know if you had some other level of RPM support in mind.
