### ISSUE TITLE
get.docker.io redirect results in empty /bin/docker file

### ISSUE THREAD

**Issue by bentheax** [spotify/docker-gc#35]
get.docker.io returns a 301 moved permanently status code to get.docker.com. cURL interprets this as success, a blank file is created in `/bin/docker`, and everything appears to have succeeded until you actually attempt to run the container and nothing happens.

It seems as though even the image on dockerhub has this issue.

The fix is simple, do one or both of:

- Use the `-L` argument to tell cURL to follow redirects
- Specify the get.docker.com url

**Comment by mbruggmann** [comment]
This was fixed in #34.
