### ISSUE TITLE
Create tags on the docker hub

### ISSUE THREAD

**Issue by aidanhs** [spotify/docker-gc#37]
...(and the git repo) to allow people to stay on a stable working version.

**Comment by mattnworb** [comment]
Thanks @aidanhs for the idea. I've just pushed a tag for `0.1` which refers to the repository as of 86874c2. 

And in case you weren't aware there is also a `latest` tag which is built/pushed for every change to the master branch.

**Comment by aidanhs** [comment]
Thanks for the tag, works great :)
Yeah I'm aware I can use latest, but I've been bitten before with the https://github.com/spotify/docker-gc repo introducing bugs on master - less frustration to stay on something that I know works!
