### ISSUE TITLE
failure to run if client and server API versions don't match

### ISSUE THREAD

**Issue by neurogenesis** [spotify/docker-gc#41]
since not everyone will be using the same version of the server API, the docker-gc client should be able detect and use the appropriate version of the docker API.

**Comment by davidxia** [comment]
Good suggestion. We're definitely open to PRs :)

On Tue, Aug 11, 2015 at 5:45 PM, ives <notifications@github.com> wrote:

> since not everyone will be using the same version of the server API, the
> docker-gc client should be able detect and use the appropriate version of
> the docker API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-gc/issues/41>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by wereHamster** [comment]
The docker daemon may be newer than the client talking to it. Since the `rm` and `rmi` commands have been in docker for a while, it is sufficient to install an old version (eg. 1.6) and docker-gc will be able to talk to all newer deamons.

**Comment by rohansingh** [comment]
We just shell out to `docker`. If there's an issue and the `docker` CLI is unable to communicate with the Docker daemon, then there's something wrong with the setup.
