### ISSUE TITLE
Running docker-gc while a pull is running corrupts the image

### ISSUE THREAD

**Issue by nistvan86** [spotify/docker-gc#43]
If a docker pull is running while docker-gc executes it deletes intermediate layers of the currently pulled image, corrupting the download. If you try to create a container from the corrupt image, it shows an error that it cannot find an intermediate image.

On a machine of mine I'm running a similar code which removes untagged images with the command:
```docker rmi $(docker images -q --filter "dangling=true")```
This has the same issues and because of that I'm running it only nightly once when there's no other maintenance method is running.

I wonder if this could be improved somehow. It would be really helpful to run docker-gc more often on eg. a Jenkins build machine, where each commit can trigger a new build with a new image and we can run out of disk space quickly.

This can be really hard to fix because of the race conditions.

**Comment by dalanlan** [comment]
I believe this should be taken care of docker itself inherently.

**Comment by dalanlan** [comment]
Check docker issue #13681
Should be addressed in 1.8.0 (didnt give it a test though)

**Comment by nistvan86** [comment]
Good finding. I think the main ticket for the issue is this: https://github.com/docker/docker/issues/8926
Closing, thanks!
