### ISSUE TITLE
Unexpected behavior of docker-gc

### ISSUE THREAD

**Issue by dalanlan** [spotify/docker-gc#44]
1 Run as a binary 
Initialization: no /etc/docker-gc-exclude && /etc/docker-gc-exclude-containers files ( empty `EXCLUDE_FROM_GC` && `EXCLUDE_CONTAINERS_FROM_GC` ENV)
Run: After the execution, i would get a /var/lib/docker-gc/exclude_container_ids file containing all of the existing containers, while /var/lib/docker-gc/exclude_ids is empty, which is not expected.

2 Run as a docker container
Simple `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc` is not gonna work.
How could it possibly function well without accessing `EXCLUDE_FROM_GC` ENV (sort of stuff)? 'Cause it's located in /etc/docker-gc-exclude-containers.
We need a volume at least.

**Comment by davidxia** [comment]
@dalanlan I think this PR fixes 1 right? https://github.com/spotify/docker-gc/pull/46

**Comment by dalanlan** [comment]
It should, which confused me a lot.

**Comment by dalanlan** [comment]
Hmm.. good to go then.
