### ISSUE TITLE
output/log which containers and images have been deleted

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-gc#55]
It would be nice if the script could output in some capacity what it had removed, to be able to trace back issues where an image/container was unexpectedly removed from a host.

The current version of the script keeps some output of what it has done in the "state directory" but this is overwritten each time the script is re-run.

For instance, I would like to be able to check /var/log/cron.log to see that docker-gc deleted image 123456 three hours ago, even if I have run the script 10 times more since then.

**Comment by pacuna** [comment]
+1

**Comment by ryneo** [comment]
+1

**Comment by konstruktoid** [comment]
Would a simple  `${STATE_DIR}/docker-gc.log` log file suffice or are you in need of script output?
