### ISSUE TITLE
Support for removing Dead containers?

### ISSUE THREAD

**Issue by flaccid** [spotify/docker-gc#60]
Thank you for docker-gc, it is working nicely for us.

What I did notice is that it doesn't currently remove `Dead` containers (or it tries and is unsuccessful).

It looks like docker-gc wants to keep them:

```
$ docker ps -a | grep Dead
45c3be6ad58e        myimage              "myproc"   4 days ago          Dead
66feab2765bd        myimage              "myproc"   4 days ago          Dead
2a45be87379e        myimage              "myproc"   4 days ago          Dead
b8d073da4fac        myimage              "myproc"   4 days ago          Dead
c0dba5cc5f20        myimage              "myproc"   4 days ago          Dead

$ grep 45c3b /var/lib/docker-gc/*
/var/lib/docker-gc/containers.all:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.exited:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.keep:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.reap.tmp:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/exclude_container_ids:45c3be6ad58e

$ grep 66fea /var/lib/docker-gc/*
/var/lib/docker-gc/containers.all:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.exited:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.keep:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.reap.tmp:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/exclude_container_ids:66feab2765bd
```

Although not necessarily common, it would be good to cover these or at least output them to a `.dead` file which can be monitored and addressed a person or another tool.

**Comment by konstruktoid** [comment]
Hi @flaccid, do you have a repeatable way to create dead containers?

**Comment by withinboredom** [comment]
Have the container exit with a non-zero exit status, that usually does the trick. After a time, docker will mark the container as dead.

**Comment by konstruktoid** [comment]
Thanks @withinboredom but either the container exists with the error code or ends up in a `Created` state.

**Comment by withinboredom** [comment]
Hmm, here's how we're getting them:

We have data-container, and a build-container. build-container has --volumes-from data-container and data-container has volumes from the filesystem.

We always see them go to Dead when the container exits with code 137, unexpectedly (someone usually stops the build). If something tries to delete them, they get marked as Dead instead of removed. My theory is that file handles were left open to the underlying FS that was shared via volumes when the container gets killed, thereby preventing it from being deleted without an `rm -f`.

**Comment by konstruktoid** [comment]
Yeah, the Dead state usually shows up here when a file system is busy and the containers exits with a non-zero, but I can't reproduce it consistently. 
Just betting on that `{{.State.Dead}}` works correctly.

**Comment by withinboredom** [comment]
give me a branch and I can run it here locally, we get them pretty regularly.

**Comment by flaccid** [comment]
@konstruktoid sorry I don't have a basic way to create them :(

**Comment by cordoval** [comment]
ping don't we usually have dead containers in kubernetes all the time?
