### ISSUE TITLE
Non-debian support, please?

### ISSUE THREAD

**Issue by benson-basis** [spotify/docker-gc#69]
I'd like to run this on my mac. Could that be facilitated?

**Comment by mattnworb** [comment]
Beyond any incompatibilities in the shell script you can also always run it as a [docker container itself](https://github.com/spotify/docker-gc#running-as-a-docker-container)

**Comment by gudata** [comment]
Why not just use the shell script directly?

**Comment by nicodewet** [comment]
Because you may run into the following:

```
Nicos-Air:docker-gc nico$ sudo ./docker-gc 
./docker-gc: line 62: pidof: command not found
Container not running 83429f340d6e015ee926e11080e66a06b5059496fda94427d93e2bd9384f880a /spr-boot-templ
```

So now, you can fix that with:

`$ brew install pidof`

But then you may get:

```
Nicos-Air:docker-gc nico$ sudo ./docker-gc 
Password:
pidof: illegal option -- s
[Fri 15 Jul 2016 21:39:04 NZST] : docker-gc : Process is already running with PID Help:
```

At which point I'm leaning towards parking this and just running it as a docker container itself whilst thinking about working on Ubuntu / Debian.

**Comment by konstruktoid** [comment]
Hi @nicodewet, and thanks for commenting. 
When released Docker for Win or Mac wasn't available and, as you pointed out, there might be issues with the script on those platforms. 
Are you having any issues when running the container?

**Comment by nicodewet** [comment]
No issues when running it as a container on mac os x as of right now following the documentation:

`$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
`

In my case, this mode of operation is just fine. 

Also, I now know that spotify-gc as a script is working just fine on the RHEL 7.2 infrastructure that I have a hand in, so life is good in terms of rolling it out on my side of the fence.
