### ISSUE TITLE
Docker-gc hangs

### ISSUE THREAD

**Issue by chris-martin** [spotify/docker-gc#75]
I just ran `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc` as specified in the readme. It reported removing a bunch of containers, and now it seems to be hanging indefinitely.

```
> docker --version
Docker version 1.8.1, build 786b29d4
```

Tried it again - on the second run, it produces the same output (it reported removing the same containers, so it seems like it didn't actually do anything) and hangs in the same place.

**Comment by mattnworb** [comment]
Was there any outcome to this @chris-martin? Is it still reproducible?

**Comment by chris-martin** [comment]
Container running <id> <name>
Container running <id> <name>
Container running <id> <name>
Container running <id> <name>

Container not running f7af2a80949fdecf98a1ee0a66862a0f08be85e7ed81d5aa562bdfcd0ece51d4 /cardforcoin_aws_run_29
Container not running fc6b550486f3757bcb52ec048f4dd678dc3e332ee2938c142dc8a689b4919dfd /cardforcoin_dev_run_57
Container not running fce318198b6bcee54642cd3db92ddc12408c9e7b4040e200667e36660c4a0693 /cardforcoin_aws_run_24
Container not running fce9b15cdc99e14ddc0d67ff5c31f6284487b15aad3b010122d541a8c4ee8c14 /cardforcoin_dev_run_24
Container not running fdaf1e204171ee3dc09a215bd18faf522adfb3580bcc1869d29eb0e6a962f57a /cardforcoin_dev_run_32
Container removed 00f3d648d714823db31a08b1b860be407dd817915565e147143f0adc03f07d79 /cardforcoin_aws_run_46
Container removed 0277450b58544242d2570733aac55d636330110a6b08f06a953713c6d1b9b051 /cardforcoin_dev_run_41
Container removed 03cc6f301ba85117b1cd9a90d605757e7abdb42d222a269e4ae98554769948f3 /cardforcoin_dev_run_63
Container removed 04a9b5db554dd2e318f6a7746ac32d1053f71c808397ac9bf109f6fa7ccea4ce /cardforcoin_dev_run_44
Container removed 0532e6df56d22f3cbd847d78b66ef29de060c5536a75030c7a115dcd14e1baa5 /cardforcoin_dev_run_52

**Comment by chris-martin** [comment]
It is reproducible (tried again just now). I haven't  done any further investigation.

The output looks like this (with many lines removed for brevity and container info redacted):

```
Container running <id> <name>
Container running <id> <name>
Container running <id> <name>
Container running <id> <name>
Container not running <id> <name>
Container not running <id> <name>
Container not running <id> <name>
Container removed <id> <name>
Container removed <id> <name>
Container removed <id> <name>
```

**Comment by chris-martin** [comment]
`top` shows a process called `kworker` consuming one CPU while the `docker-gc` container is running.

`docker stop` is sufficient to kill it.

**Comment by mattnworb** [comment]
Can you share some details of your setup like OS/distribution, docker version, what version/commit of docker-gc this is, etc?

**Comment by chris-martin** [comment]
I'm just running exactly the command given above, so the docker-gc version... whatever's on Docker Hub, right?

The Docker version is also given in the first comment.

My distro is NixOS 15.09.

**Comment by mattnworb** [comment]
I'm afraid I don't have a NixOS setup to try to easily reproduce this on. 

One thing you could try is to grab the `docker-gc` from master and run that with `sudo bash -x docker-gc` and see if you get the same hanging, and if so let us know which command seems to cause that. 

Since it's not an OS we are familiar with any more hints as to what the issue might be would be really helpful to resolve it.

**Comment by chris-martin** [comment]
Oh, I see what's going on now. The extra output from running it this way helps. It's at this line:

    xargs -n 1 $DOCKER rm --volumes=true < containers.reap &>/dev/null || true

If I periodically run `docker ps -a | wc -l` I can see that it *is* removing containers, not hanging. Maybe it should print something for each container so you can tell that it's making progress?

**Comment by skorokithakis** [comment]
Same thing happened to me. It seems to be taking ~3 seconds to remove an image, with no output in the command line.
