### ISSUE TITLE
Publish packages to bintray?

### ISSUE THREAD

**Issue by dlackty** [spotify/docker-gc#81]
Thanks for making this useful tool. 

However, the current installation process requires users to manually build system packages, and it would be great if these packaged can be pre-built and published to public service like Bintray.

AFAIK, there's an official Spotify team page on Bintray: https://bintray.com/spotify

**Comment by mattnworb** [comment]
Hey @dlackty thanks for the great idea, we will definitely look into adding a package to bintray for docker-gc.

**Comment by willejs** [comment]
@mattnworb even adding the deb to github releases would be great. You could do this through travis too. Would you accept a PR?

**Comment by mattnworb** [comment]
Thanks for the suggestion. I tried to set up something through bintray but ironically they do not allow a repo to be prefixed with `docker-` if it is publishing Debian packages.

We have an apt repo set up for our [helios project](https://github.com/spotify/helios) so it might just be easiest for us to add this to there.

**Comment by scoopex** [comment]
Why not publishing the packages on the github/releases section of this project?
