### ISSUE TITLE
Allow passing "EXCLUDE_CONTAINERS" and "EXCLUDE_IMAGES" as environmental vars

### ISSUE THREAD

**Issue by emmetog** [spotify/docker-gc#83]
## Background

Right now to set images and containers to exclude from the cleanup we need to:
1) Write the lists to files
2) Map the files into the docker-gc container

Far simpler to allow environmental variables which contain a comma separated list of the containers or images.

Having to put the excluded images and containers into files and then map the volume complicates things a lot in some cases, here's an example: Jenkins (which is dockerized but has control over the hosts docker server by mounting the docker socket as a volume) runs the docker-gc regularly. In order to specify the containers and images to exclude, Jenkins needs to first put the files on the host (which requires additional volumes mounted into Jenkins) and then map those same files into the docker gc container. If we could pass in the excluded images and containers as environmental variables when the docker gc container is run it would be much simpler.
## The proposal

This proposal is for two new environmental variables called `EXCLUDE_CONTAINERS` and `EXCLUDE_IMAGES`. They would be used as follows (example):

```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e EXCLUDE_CONTAINERS=container-one,container-two -e EXCLUDE_IMAGES=image-one,image-two spotify/docker-gc
```
## Functionality

The functionality would be:
Excluded containers:
- If the EXCLUDE_CONTAINERS environmental variable is set then it takes priority, if the `/etc/docker-gc-exclude-containers` file exists it is ignored.
- If no EXCLUDE_CONTAINERS environmental variable is set then the behaviour is the same as right now; we check the `/etc/docker-gc-exclude-containers` file and get the excluded containers from there (or exclude no containers if the file doesn't exist).

Excluded images:
- If the EXCLUDE_IMAGES environmental variable is set then it takes priority, if the `/etc/docker-gc-exclude` file exists it is ignored.
- If no EXCLUDE_IMAGES environmental variable is set then the behaviour is the same as right now; we check the `/etc/docker-gc-exclude` file and get the excluded images from there (or exclude no images if the file doesn't exist).

**Comment by mattnworb** [comment]
@emmetog thanks for the detailed writeup. I can't see any reason why the "exclude container/image" logic couldn't be extended to give priority to an environment file before reading from the file (whose path can be overridden with an existing environment file already).

**Comment by emmetog** [comment]
Hi @mattnworb, I'm not sure I understand your comment.
> I can't see any reason why the "exclude container/image" logic couldn't be extended to give priority to an environment file before reading from the file (whose path can be overridden with an existing environment file already)

When you say "environment file" you mean an environment variable, right? Just in case there's a misunderstanding, I'm proposing environment variables, not files.

**Comment by mattnworb** [comment]
Right, I just mean that I can't see any reason to not implement this proposal :smile:

**Comment by mattnworb** [comment]
and to be extra clear I would be happy to merge a PR that implemented this proposal
