### ISSUE TITLE
docker-gc ignores EXCLUDE_FROM_GC on Docker 1.10

### ISSUE THREAD

**Issue by tomxtobin** [spotify/docker-gc#85]
After upgrading to Docker 1.10, `docker-gc` ignored my `EXCLUDE_FROM_GC` setting and removed nearly all my local Docker images.

**Comment by mattnworb** [comment]
It sounds to me like Docker 1.10 [changes the IDs of all of your images when migrating to the new storage format](https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration), so your excludes file will need to change it's contents.

**Comment by tomxtobin** [comment]
My excludes file only has labels, not IDs, e.g.:
```
debian:8
python:3\.5-alpine
rethinkdb:latest
```

**Comment by mattnworb** [comment]
Sorry to hear it caused an issue for you :disappointed: To be quite honest though at Spotify we are a few versions of Docker behind, and AFAIK Docker 1.10 is just freshly released, so I am not entirely surprised that there may be conflicts - which sound like the new storage engine could be at play.

**Comment by tomxtobin** [comment]
It wasn't a huge deal; I noticed it on my local dev machine, and it was nothing that couldn't be fixed by re-pulling and re-building. :-)

**Comment by zerthimon** [comment]
This PS fixes the issue https://github.com/spotify/docker-gc/pull/93 for docker version >=1.10 deployments.
Works with docker pre 1.10
