### ISSUE TITLE
Failed to run docker-gc due to a invalid syntax error

### ISSUE THREAD

**Issue by gizmochief7** [spotify/docker-gc#88]
I'm trying to run docker-gc on my Raspberry Pi. This is the first time I've attempted to run it. I checked it out, built and installed it with only these issues

`...`
`warning: the authors of lintian do not recommend running it with root privileges!`
`E: docker-gc: no-copyright-file`
`E: docker-gc: extended-description-is-empty`
`W: docker-gc: binary-without-manpage usr/sbin/docker-gc`
`Finished running lintian.`

I added an excludes file to my default location that just has "latest" in it.
I run the command manually  and the results are...

`$ docker-gc`
`Container not running 026614557a1a053dab3225b85216d14169fc8f9bca8ff9011319db41086d5133 /distracted_visvesvaraya`
`...`
`Container not running ffc72f6f12f8202af21fe3204ace4c2867277b213bf13d4c5457c1d35442c035 /sharp_ritchie`

And then this is the error thrown at the end...

`date: invalid date ‘0001-01-01 00:00:00’`
`/usr/sbin/docker-gc: line 102: 1456619521 - : syntax error: operand expected (error token is "- ")`

No images were removed after this error was thrown. Is this a bug or did I just overlook something?

**Comment by mattnworb** [comment]
[the link in question](https://github.com/spotify/docker-gc/blob/3c4cecef4ec38964a656dca9bfa61354d9da0d2c/docker-gc#L102)

what version of bash does your device use?

**Comment by gizmochief7** [comment]
Thanks for the response. I'm not sure of the bash version off the top of my head. When I get home i'll find out and post back. I'll also update it just in case.

**Comment by gizmochief7** [comment]
The version currently installed is

`sudo bash --version`
`GNU bash, version 4.3.30(1)-release (arm-unknown-linux-gnueabihf)`

and after trying to upgrade, it said it was the latest already.

`sudo apt-get install bash`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`bash is already the newest version.`
`0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.`
