### ISSUE TITLE
deleting orphaned volumes

### ISSUE THREAD

**Issue by nschloe** [spotify/docker-gc#90]
Docker-gc does a really nice job here, but one thing it doesn't do: Cleaning up dangling volumes. To this end, I'm running

``` sh
docker volume ls -qf dangling=true | xargs -r docker volume rm
```

as a cronjob; see https://github.com/chadoe/docker-cleanup-volumes. It'd perhaps be worthwhile including it into docker-gc as well.

**Comment by zerthimon** [comment]
+1

**Comment by caiofbpa** [comment]
+1

**Comment by sfrique** [comment]
+1

**Comment by harrybvp** [comment]
+1

**Comment by zerthimon** [comment]
I'd really appreciate it if I could get an explanation from the maintainer of docker-gc why this feature is not implemented yet ?
I may be able to provide a PR (if it has a chance to be accepted). Are there any concrete reasons against this functionality in the first place ?

**Comment by zerthimon** [comment]
So there is already a PR for this: https://github.com/spotify/docker-gc/pull/142

**Comment by davidxia** [comment]
fixed by https://github.com/spotify/docker-gc/pull/142
