### ISSUE TITLE
Broken containers break docker-gc

### ISSUE THREAD

**Issue by carlpett** [spotify/docker-gc#95]
## Description

For some reason I'm not quite sure of yet, we sometimes end up with entries in /var/lib/docker/containers/ that docker does not recognize. This causes errors like `Error: No such image or container: 3801e6aeaf57c....`, which then causes docker-gc to error out before removing any containers. This builds up, and then we (since we apparently cron didn't send mail to the right place) have full disk.
## How to reproduce

Not sure, sadly. 
## What do you expect

Ignore the missing container and remove the rest. Display summary afterwards with errors encountered.
## What happened instead

No containers removed
## Software:
- bash version: 4.2.46(1)
- docker version: 1.10.2 and 1.9.0

**Comment by GoodHaHa** [comment]
I get the same problems.

**Comment by chbatey** [comment]
This happens when there is a dead container

**Comment by DrEsteban** [comment]
What is the solution for dead containers?
